### ISSUE TITLE
Sending photo by mail doesn't work.

### ISSUE THREAD

**Issue by IrynaChernenko** [novaphotos/nova-ios-app#135] opened 2014-07-08 15:55 UTC
iPhone 4S
iOS 7.0.6

Steps to reproduse:
1. Install and run app on device.
2. Tap camera roll button on the bottom of camera mode screen.
3. On the screen where camera is active tap the Gallery button.
4. Give the app permission to access your folder with photos and videos if it asks you for it.
5. Choose any image and tap on it.
7. After image is opened tap on the button in left bottom corner of the screen to expand menu.
8. Tap “mail” button which is in bottom row.

Actual result: sending photo by mail doesn't work. Nothing happens after Tap “mail” button

Expected result: sending screen opens after tap "mail" button

Video: https://www.dropbox.com/sc/nrm5soixk22flnv/AAC1KcaiMtoh1O9EwxASnAV_a

**Comment by joewalnes** [comment] 2014-08-10 22:56
I've tested on 3 phones and I'm unable to reproduce this. Closing for now.

**Closed as completed by joewalnes** 2014-08-10 22:56 UTC

**Comment by IrynaChernenko** [comment] 2014-08-12 13:35
iPhone 4s, iOS 7.1.2
Issue is not reproduced
